logo_title: 恶魔萝莉控

style: white

favicon: /favicon.png

menu:
  归档: /archives
  友链: /links
  关于: /about
  网盘: https://imgblz.cn

# 做了域名限制，请改成自己的 KEY
# 若关闭valine 设置enable为false
valine:
  enable: false
  appId: CaQKuPQDfnfPFUkTw6MMt8ME-gzGzoHsz
  appKey: uWuwGS1xiIwh3zHKENc7ubyL

highlight:
  enable: false

cdn:
  enabled: true
  url: https://cdn.jsdelivr.net/gh/15601560/blog
